version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: social-network-db
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: social_network_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_import:/var/lib/postgresql/data/import
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_network"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - social-network-net

volumes:
  postgres_data:
    driver: local

networks:
  social-network-net:
    driver: bridge
